#!/usr/bin/env bash
# Usage: setup yum-utils
# Summary: Install yum utilities
# Help: Install yum utilities such as yumdownloader on RHEL/CentOS

source basics
source rhel6-utils

use_strict_mode

exit_if_package_is_installed yum-utils
yum_install yum-utils
