#!/usr/bin/env bash
# Usage: setup git
# Summary: Install git 2
# Help: Install the git version control system version 2 on RHEL/CentOS
# Requires the git2u rpm from the IUS repository to be available

source basics
source rhel6-utils

set -o errexit

sudo yum install -y git2u
