#!/usr/bin/env bash
# Usage: setup git
# Summary: Install git 2

source basics

strict_mode_on
exit_if_is_on_path git

mkdir -p "${HOME}/tmp"
push_dir "${HOME}/tmp"
wget https://www.kernel.org/pub/software/scm/git/git-2.7.0.tar.gz
pop_dir
