#!/usr/bin/env bash
# Usage: setup git
# Summary: Install git 2
# Help: Install the git version control system version 2 on RHEL/CentOS
# Requires the IUS repository

set -o errexit

sudo yum install -y git2u
