#!/usr/bin/env bash
# Usage: jiff install [package]
# Summary: Install and configure a system package

source basics
source ubuntu

strict_mode_on

case "${1}" in
"ranger" | "git" )
  install "${package}"
  ;;
* )
  echo "Usage: jiff install [ranger|git]"
  ;;
esac
