#!/usr/bin/env bash
# Usage: jiff install [package]
# Summary: Install and configure a system package

source basics
source platform

strict_mode_on

package="${1}"

case "${package}" in
* )
  install_package "${package}"
  ;;
esac
