#!/usr/bin/env bash
# Usage: jiff use [rhel-6.7|centos-6.5|ubuntu-14.04|ubuntu-15.10|auto|none]
# Summary: Add system-specific commands from the named system

source basiclib

strict_mode_on

# Provide jiff completions
if match "${1:-}" "--complete"; then
  cat <<EOM
rhel-6.7
centos-6.5
ubuntu-14.04
ubuntu-15.10
auto
none
EOM
  exit
fi

LibExec="${_JIFF_ROOT}/libexec"
CurrentLink="${LibExec}/system/current"

make_links () {
  local system
  local file
  local link

  system="${1}"

  make_symlink "${CurrentLink}" "${system}"
  for file in ${CurrentLink}/jiff-*; do
    link="$(base_name "${file}")"
    make_symlink "${LibExec}/${link}" "${file}"
  done
}

jiff_auto () {
  local system

  exit_if_is_link "${CurrentLink}"
  system="$(detect_os)"
  jiff use "${system}"
}

remove_links () {
  local file
  local link

  for file in ${CurrentLink}/jiff-*; do
    link="$(base_name "${file}")"
    rm -f "${LibExec}/${link}"
  done
  rm -f "${CurrentLink}"
}

usage () {
  echo "Usage: jiff use [rhel-6.7|centos-6.5|ubuntu-14.04|ubuntu-15.10|auto|none]"
}

report_current () {
  if is_link "${CurrentLink}"; then
    current="$(readlink "${CurrentLink}")"
    current="${current##*/}"
  else
    current=none
  fi
  echo "Currently using: ${current}"
}

system="${1:-}"

case "${system}" in
"rhel-6.7" | "centos-6.5" | "ubuntu-14.04" | "ubuntu-15.10" )
  make_links "${system}"
  ;;
"auto" )
  jiff_auto
  ;;
"none" )
  remove_links
  ;;
* )
  usage
  report_current
  ;;
esac
