#!/usr/bin/env bash
# Usage: jiff use [rhel-6|centos-6|ubuntu-14.04|auto|none]
# Summary: Add system-specific commands from the named system

source basics

strict_mode_on

# Provide jiff completions
if match "${1:-}" "--complete"; then
  cat <<EOM
rhel6
centos
auto
none
EOM
  exit
fi

libexec="${_JIFF_ROOT}/libexec"
system_dir="${libexec}/system"
link="${system_dir}/current"
system="${1:-}"

case "${system}" in
"rhel-6" | "centos-6" | "ubuntu-14.04" )
  make_symlink "${link}" "${system}"
  for file in ${link}/*; do
    nlink="$(base_name "${file}")"
    make_symlink "${libexec}/${nlink}" "${file}"
  done
  ;;
"auto" )
  exit_if_is_link "${link}"
  system="$(detect_os)"
  jiff use "${system}"
  ;;
"none" )
  for file in ${link}/*; do
    nlink="$(base_name "${file}")"
    rm -f "${libexec}/${nlink}"
  done
  rm -f "${link}"
  ;;
* )
  echo "Usage: jiff use [rhel-6|centos-6|ubuntu-14.04|auto|none]"
  [[ -h "${link}" ]] && current="$(readlink "${link}")" && current="${current##*/}"
  [[ -z "${current:-}" ]] && current=none
  echo "Currently using: ${current}"
  ;;
esac
