#!/usr/bin/env bash
# Usage: jiff dotfiles
# Summary: Link dotfiles to home directory locations

source basics
source platform

strict_mode_on

#exit_if_is_directory "${HOME}/dotfiles"
install_package git
install_package ranger
push_dir "${HOME}"
touch .hushlogin
#mkdir -pm 700 dotfiles
#setfacl -m g::-,o:-,d:g::-,d:o:- dotfiles
#git clone git://github.com/binaryphile/dotfiles
#cd dotfiles
#git remote set-url origin git@github.com:binaryphile/dotfiles
#cd system
#git update-index --assume-unchanged current
#rm current
#ln -sfT $(hostname) current
#cd "${HOME}"
for file in ctags gemrc gitconfig gitignore_global inputrc tmux.conf Xmodmap pryrc ruby-version; do
  make_symlink ".${file}" "${HOME}/dotfiles/${file}"
done
mkdir -pm 700 .ssh
for file in known_hosts config; do
  make_symlink ".ssh/${file}" "${HOME}/dotfiles/ssh/${file}"
done
mkdir -p .bundle
make_symlink ".bundle/config" "${HOME}/dotfiles/bundle-config"
mkdir -p .config
cd .config
mkdir -p fish
make_symlink "fish/config.fish" "${HOME}/dotfiles/fish/config.fish"
mkdir -p ranger
ranger --copy-config=all
for file in rc.conf rifle.conf scope.sh commands.py; do
  make_symlink "ranger/${file}" "${HOME}/dotfiles/ranger/${file}"
done
pop_dir
