#!/usr/bin/env bash

source shell.sh
source path.sh

main() {
  libexec_path="$(path::abs_dirname "$0")"
  lib_path="$(path::abs_dirname "${libexec_path}/../lib/")"
  export _JIFF_ROOT="$(path::abs_dirname "$libexec_path")"
  export PATH="${lib_path}:${libexec_path}:$PATH"

  command="$1"
  case "$command" in
  "" | "-h" | "--help" )
    exec jiff-help
    ;;
  * )
    command_path="$(command -v "jiff-$command" || :)"
    if [ ! -x "$command_path" ]; then
      echo "jiff: no such task \`$command'" >&2
      exit 1
    fi

    shift
    exec "$command_path" "$@"
    ;;
  esac
}

return 0 2>/dev/null || :
sh::strict_mode on
main "$@"
