#!/usr/bin/env bash
# Usage: setup slash-git [admin group (default: prodadm)]
# Summary: Set up git repository in the root filesystem

source basics

strict_mode_on

exit_if_is_directory /.git
setup git
push_dir /
make_group_dir .git "${1:-}"
git init
make_group_file .gitignore "${1:-}"
cat <<EOM > .gitignore
*
id_*
*.pem
*.pfx
*.key
*.key.*
EOM
git add --force .gitignore
git commit --message "initial commit"
pop_dir
