#!/usr/bin/env bash
# Usage: setup rhel6
# Summary: Switch system-specific commands to RHEL6/CentOS6
# Help: Switch system-specific commands to RHEL6/CentOS6

set -o errexit

for file in ${_SETUP_ROOT}/libexec/system/rhel6/*; do
  ln -sf "${file}" "${_SETUP_ROOT}/libexec/${file##*/}"
done
