#!/usr/bin/env bash
# Usage: setup use [rhel6|centos|auto|none]
# Summary: Add system-specific commands from the named system

source basics

strict_mode_on

# Provide setup completions
if match "${1:-}" "--complete"; then
  cat <<EOM
rhel6
centos
auto
none
EOM
  exit
fi

libexec="${_SETUP_ROOT}/libexec"
system_dir="${libexec}/system"
link="${system_dir}/current"
system="${1:-}"

case "${system}" in
"rhel6" | "centos" )
  chosen_dir="${system_dir}/${system}"
  make_symlink "${link}" "${chosen_dir}"
  for file in ${chosen_dir}/*; do
    link="$(base_name "${file}")"
    make_symlink "${libexec}/${link}" "${file}"
  done
  ;;
"auto" )
  system="$(detect_os)"
  setup use "${system}"
  ;;
"none" )
  system="$(readlink "${link}")"
  system="$(base_name "${system}")"
  chosen_dir="${system_dir}/${system}"
  rm -f "${link}"
  for file in ${chosen_dir}/*; do
    link="$(base_name "${file}")"
    rm -f "${libexec}/${link}"
  done
  ;;
* )
  echo "Usage: setup use [rhel6|centos|auto|none]"
  [[ -h "${link}" ]] && current="$(readlink "${link}")" && current="${current##*/}"
  [[ -z "${current:-}" ]] && current=none
  echo "Currently using: ${current}"
  ;;
esac
