#!/usr/bin/env bash
# Usage: setup basher [admin group (default: prodadm)]
# Summary: Set up basher package manager

source basics

strict_mode_on

exit_if_is_in_path basher
setup slash-git
push_dir /etc/profile.d
cat <<EOM | sudo tee basher.sh
if [[ "$(id -u)" -ne 0 ]] && [[ -z "${BASHER_ROOT}" ]]; then
  export BASHER_ROOT=/opt/basher
  export PATH="${PATH}:/opt/basher/bin"
  eval "$(basher init -)"
fi
EOM
git add --force basher.sh
git commit --message "basher"
cd /opt
make_group_dir basher
git clone git://github.com/basherpm/basher
cd basher/libexec
substitute_in_file basher '${bin_path}:${PATH}' '${PATH}:${bin_path}'
substitute_in_file basher-init '$BASHER_ROOT/cellar/bin:$PATH' '$PATH:$BASHER_ROOT/cellar/bin'
pop_dir
