#!/usr/bin/env bash
# Usage: setup slash-git
# Summary: Set up git repository in the root filesystem

source basics

strict_mode_on

setup git
exit_if_is_directory /.git
push_dir /
sudo mkdir .git
sudo chown "${USER}:${1:-prodadm}" .git
chmod g+s .git
setfacl -m g::rwx,d:g::rwx .git
git init
sudo touch .gitignore
sudo chown "${USER}:${1:-prodadm}" .gitignore
chmod g+rw .gitignore
cat > .gitignore <<EOM
*
id_*
*.pem
*.pfx
*.key
*.key.*
EOM
git add --force .gitignore
git commit --message "initial commit"
pop_dir
