#!/usr/bin/env bash
# Usage: setup use [rhel6|none]
# Summary: Add system-specific commands from the named system
# Help: Add system-specific commands from the named system

set -o errexit

# Provide setup completions
if [[ "${1}" == "--complete" ]]; then
  echo rhel6
  echo none
  exit
fi

libexec="${_SETUP_ROOT}/libexec"
system_dir="${libexec}/system"
link="${system_dir}/current"
system="${1}"

case "${system}" in
"rhel6" )
  chosen_dir="${system_dir}/${system}"
  ln -sfT "${chosen_dir}" "${link}"
  for file in ${chosen_dir}/*; do
    ln -sf "${file}" "${libexec}/${file##*/}"
  done
  ;;
"none" )
  system="$(readlink "${link}")"
  system="${system##*/}"
  chosen_dir="${system_dir}/${system}"
  rm -f "${link}"
  for file in ${chosen_dir}/*; do
    rm -f "${libexec}/${file##*/}"
  done
  ;;
* )
  echo "Usage: setup use [rhel6|none]"
  [[ -h "${link}" ]] && current="$(readlink "${link}")" && current="${current##*/}"
  [[ -z "${current:-}" ]] && current=none
  echo "Currently using: ${current}"
  ;;
esac

