#!/usr/bin/env bash
# Usage: setup choose [rhel6|none]
# Summary: Add system-specific commands from the named system
# Help: Add system-specific commands from the named system

set -o errexit

# Provide setup completions
if [[ "${1}" == "--complete" ]]; then
  echo rhel6
  echo none
  exit
fi

libexec="${_SETUP_ROOT}/libexec"
system_dir="${libexec}/system"
link="${system_dir}/current"
system="${1}"

case "${system}" in
"rhel6" )
  new_dir="${system_dir}/${system}"
  ln -sfT "${new_dir}" "${link}"
  for file in ${new_dir}/*; do
    ln -sf "${file}" "${libexec}/${file##*/}"
  done
  ;;
"none" )
  system="$(readlink "${link}")"
  system="${system##*/}"
  new_dir="${system_dir}/${system}"
  rm -f "${link}"
  for file in ${new_dir}/*; do
    rm -f "${libexec}/${file##*/}"
  done
  ;;
* )
  echo "Usage: setup system [rhel6|none]"
  ;;
esac

