#!/usr/bin/env bash
# Usage: jiff yum-utils
# Summary: Install yum utilities
# Help: Install yum utilities such as yumdownloader on RHEL/CentOS

source basics
source red

strict_mode_on

exit_if_package_is_installed yum-utils
yum_install yum-utils
