#!/usr/bin/env bash
# Usage: jiff stgit
# Summary: Install stacked git

source basics

strict_mode_on
exit_if_is_on_path stg

jiff install git
mkdir -p "${HOME}/tmp"
push_dir "${HOME}/tmp"
git clone git://repo.or.cz/stgit.git
cd stgit
make prefix=/usr all doc
sudo make prefix=/usr install install-doc
cd ..
rm -rf stgit
pop_dir
